Updating text

diff --git a/.github/workflows/mirror-pr.yml b/.github/workflows/mirror-pr.yml
--- a/.github/workflows/mirror-pr.yml
+++ b/.github/workflows/mirror-pr.yml
@@ -235,26 +235,33 @@ jobs:
             WIP="false"
           fi
 
-          # Update the Merge Request in GitLab
-          RESPONSE=$(curl --silent --write-out "HTTPSTATUS:%{http_code}" \
-            --header "PRIVATE-TOKEN: ${{ secrets.GITLAB_TOKEN }}" \
-            --header "Content-Type: application/json" \
-            --data '{
-              "source_branch": "'"${PR_SOURCE_BRANCH}"'",
-              "target_branch": "'"${PR_TARGET_BRANCH}"'",
-              "title": "'"${MR_TITLE}"'",
-              "description": '"${FULL_DESCRIPTION_ESCAPED}"',
-              "work_in_progress": "'"${WIP}"'"
-            }' "https://gitlab.com/api/v4/projects/${GITLAB_PROJECT_ID}/merge_requests/${GITLAB_MR_ID}")
+          MR_ID=$(curl --silent --header "PRIVATE-TOKEN: ${{ secrets.GITLAB_TOKEN }}" \
+            "https://gitlab.com/api/v4/projects/${GITLAB_PROJECT_ID}/merge_requests?source_branch=${PR_SOURCE_BRANCH}" | jq '.[0].iid')
 
-          # Extract the HTTP status code
-          HTTP_STATUS=$(echo "$RESPONSE" | tr -d '\n' | sed -e 's/.*HTTPSTATUS://')
+          if [ -n "${MR_ID}" ]; then
+            # Update the Merge Request in GitLab
+            RESPONSE=$(curl --silent --write-out "HTTPSTATUS:%{http_code}" \
+              --header "PRIVATE-TOKEN: ${{ secrets.GITLAB_TOKEN }}" \
+              --header "Content-Type: application/json" \
+              --data '{
+                "title": "'"${MR_TITLE}"'",
+                "description": '"${FULL_DESCRIPTION_ESCAPED}"',
+                "work_in_progress": "'"${WIP}"'"
+              }' \
+              --request PUT "https://gitlab.com/api/v4/projects/${GITLAB_PROJECT_ID}/merge_requests/${MR_ID}")
 
-          # Log the response for debugging
-          echo "Response: ${RESPONSE}"
+            # Extract the HTTP status code
+            HTTP_STATUS=$(echo "$RESPONSE" | tr -d '\n' | sed -e 's/.*HTTPSTATUS://')
 
-          # Validate the response
-          if [ "${HTTP_STATUS}" -ne 200 ]; then
-            echo "Failed to update Merge Request. HTTP Status Code: $HTTP_STATUS"
+            # Log the response for debugging
+            echo "Response: ${RESPONSE}"
+
+            # Validate the response
+            if [ "${HTTP_STATUS}" -ne 200 ]; then
+              echo "Failed to update Merge Request. HTTP Status Code: $HTTP_STATUS"
+              exit 1
+            fi
+          else
+            echo "Could not find a MR for this PR, make sure it is created."
             exit 1
           fi
