better quality

diff --git a/.github/workflows/mirror-pr.yml b/.github/workflows/mirror-pr.yml
--- a/.github/workflows/mirror-pr.yml
+++ b/.github/workflows/mirror-pr.yml
@@ -98,19 +98,7 @@ jobs:
           GITLAB_PROJECT_ID: ${{ env.GITLAB_PROJECT_ID }}
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Prepare PR description
-        id: prepare_pr_description
-        uses: ./.github/actions/prepare-pr-description
-        with:
-          pr_title: ${{ github.event.pull_request.title }}
-          pr_url: ${{ github.event.pull_request.html_url }}
-          pr_description: ${{ github.event.pull_request.body }}
-          gitlab_project_id: ${{ env.GITLAB_PROJECT_ID }}
-          gitlab_token: ${{ secrets.GITLAB_TOKEN }}
-          pr_target_branch: ${{ env.TARGET_BRANCH }}
-
-      - name: Handle PR opened
-        if: github.event.action == 'opened'
+      - name: Open or update MR
         shell: bash
         run: |
           set -x
@@ -121,17 +109,27 @@ jobs:
           PR_DRAFT="${{ github.event.pull_request.draft }}"
           PR_URL="${{ github.event.pull_request.html_url }}"
 
-          PR_DESCRIPTION=${{ steps.prepare_pr_description.outputs.full_description }}
+          PR_DESCRIPTION_ESCAPED=$(jq -Rsa . <<< "${{ inputs.pr_description }}")
 
           # Fetch the GitLab MR template
-          TEMPLATE_URL="https://gitlab.com/api/v4/projects/${GITLAB_PROJECT_ID}/repository/files/.gitlab%2Fmerge_request_templates%2Fdefault.md/raw?ref=${PR_TARGET_BRANCH}"
-          TEMPLATE_CONTENT=$(curl --silent --header "PRIVATE-TOKEN: ${{ secrets.GITLAB_TOKEN }}" "${TEMPLATE_URL}")
+          TEMPLATE_URL="https://gitlab.com/api/v4/projects/${{ inputs.gitlab_project_id }}/repository/files/.gitlab%2Fmerge_request_templates%2Fdefault.md/raw?ref=${{ inputs.pr_target_branch }}"
+          TEMPLATE_CONTENT=$(curl --silent --header "PRIVATE-TOKEN: ${{ inputs.gitlab_token }}" "${TEMPLATE_URL}")
 
           # Ensure the template was fetched successfully
           if [ -z "$TEMPLATE_CONTENT" ]; then
-            echo "Failed to fetch GitLab MR template from ${TEMPLATE_URL}"
+            echo "Failed to fetch GitLab MR template"
             exit 1
           fi
+
+          # Remove the first line of the template
+          TEMPLATE_CONTENT=$(echo "${TEMPLATE_CONTENT}" | sed '1d')
+
+          # Combine the PR description and the template content
+          FULL_DESCRIPTION=$(printf "Automatically updated from GitHub PR: %s\n\n%s\n\n---\n\n%s" \
+            "${{ inputs.pr_url }}" "$(echo $PR_DESCRIPTION_ESCAPED | jq -r)" "$TEMPLATE_CONTENT")
+
+          # Escape the full description using jq for JSON safety
+          FULL_DESCRIPTION_ESCAPED=$(jq -Rsa . <<< "$FULL_DESCRIPTION")
 
           # Define title and WIP status
           if [ "${PR_DRAFT}" = "true" ]; then
@@ -142,28 +140,53 @@ jobs:
             WIP="false"
           fi
 
-          # Create the Merge Request in GitLab
-          RESPONSE=$(curl --silent --write-out "HTTPSTATUS:%{http_code}" \
-            --header "PRIVATE-TOKEN: ${{ secrets.GITLAB_TOKEN }}" \
-            --header "Content-Type: application/json" \
-            --data '{
-              "source_branch": "'"${PR_SOURCE_BRANCH}"'",
-              "target_branch": "'"${PR_TARGET_BRANCH}"'",
-              "title": "'"${MR_TITLE}"'",
-              "description": '"${FULL_DESCRIPTION_ESCAPED}"',
-              "work_in_progress": "'"${WIP}"'"
-            }' "https://gitlab.com/api/v4/projects/${GITLAB_PROJECT_ID}/merge_requests")
+          if [ -n "${MR_ID}" ]; then
+            # Update the Merge Request in GitLab
+            RESPONSE=$(curl --silent --write-out "HTTPSTATUS:%{http_code}" \
+              --header "PRIVATE-TOKEN: ${{ secrets.GITLAB_TOKEN }}" \
+              --header "Content-Type: application/json" \
+              --data '{
+                "title": "'"${MR_TITLE}"'",
+                "description": '"${FULL_DESCRIPTION_ESCAPED}"',
+                "work_in_progress": "'"${WIP}"'"
+              }' \
+              --request PUT "https://gitlab.com/api/v4/projects/${GITLAB_PROJECT_ID}/merge_requests/${MR_ID}")
 
-          # Extract the HTTP status code
-          HTTP_STATUS=$(echo "$RESPONSE" | tr -d '\n' | sed -e 's/.*HTTPSTATUS://')
+            # Extract the HTTP status code
+            HTTP_STATUS=$(echo "$RESPONSE" | tr -d '\n' | sed -e 's/.*HTTPSTATUS://')
 
-          # Log the response for debugging
-          echo "Response: ${RESPONSE}"
+            # Log the response for debugging
+            echo "Response: ${RESPONSE}"
 
-          # Validate the response
-          if [ "${HTTP_STATUS}" -ne 201 ]; then
-            echo "Failed to create Merge Request. HTTP Status Code: $HTTP_STATUS"
-            exit 1
+            # Validate the response
+            if [ "${HTTP_STATUS}" -ne 200 ]; then
+              echo "Failed to update Merge Request. HTTP Status Code: $HTTP_STATUS"
+              exit 1
+            fi
+          else
+            # Create the Merge Request in GitLab
+            RESPONSE=$(curl --silent --write-out "HTTPSTATUS:%{http_code}" \
+              --header "PRIVATE-TOKEN: ${{ secrets.GITLAB_TOKEN }}" \
+              --header "Content-Type: application/json" \
+              --data '{
+                "source_branch": "'"${PR_SOURCE_BRANCH}"'",
+                "target_branch": "'"${PR_TARGET_BRANCH}"'",
+                "title": "'"${MR_TITLE}"'",
+                "description": '"${FULL_DESCRIPTION_ESCAPED}"',
+                "work_in_progress": "'"${WIP}"'"
+              }' "https://gitlab.com/api/v4/projects/${GITLAB_PROJECT_ID}/merge_requests")
+
+            # Extract the HTTP status code
+            HTTP_STATUS=$(echo "$RESPONSE" | tr -d '\n' | sed -e 's/.*HTTPSTATUS://')
+
+            # Log the response for debugging
+            echo "Response: ${RESPONSE}"
+
+            # Validate the response
+            if [ "${HTTP_STATUS}" -ne 201 ]; then
+              echo "Failed to create Merge Request. HTTP Status Code: $HTTP_STATUS"
+              exit 1
+            fi
           fi
 
       - name: Handle PR reopened
@@ -190,65 +213,50 @@ jobs:
             exit 1
           fi
 
-      - name: Handle PR updated (Text)
-        if: github.event.action == 'edited' || github.event.action == 'synchronize'
+      - name: Handle PR closed
+        if: github.event.action == 'closed'
         shell: bash
         run: |
           set -x
 
           # Define variables
-          PR_TITLE="${{ github.event.pull_request.title }}"
           PR_SOURCE_BRANCH="PullRequest_${{ github.event.number }}"
-          PR_DRAFT="${{ github.event.pull_request.draft }}"
           PR_URL="${{ github.event.pull_request.html_url }}"
-          PR_DESCRIPTION=${{ steps.prepare_pr_description.outputs.full_description }}
 
-          # Fetch the GitLab MR template
-          TEMPLATE_URL="https://gitlab.com/api/v4/projects/${GITLAB_PROJECT_ID}/repository/files/.gitlab%2Fmerge_request_templates%2Fdefault.md/raw?ref=${PR_TARGET_BRANCH}"
-          TEMPLATE_CONTENT=$(curl --silent --header "PRIVATE-TOKEN: ${{ secrets.GITLAB_TOKEN }}" "${TEMPLATE_URL}")
+          # Check if the PR is merged or closed
+          if [ "${{ github.event.pull_request.merged }}" == "false" ]; then
+            echo "PR closed without merge. Proceeding to close GitLab MR."
 
-          # Ensure the template was fetched successfully
-          if [ -z "$TEMPLATE_CONTENT" ]; then
-            echo "Failed to fetch GitLab MR template from ${TEMPLATE_URL}"
-            exit 1
-          fi
+            # Fetch the GitLab MR ID based on the source branch
+            MR_ID=$(curl --silent --header "PRIVATE-TOKEN: ${{ secrets.GITLAB_TOKEN }}" \
+              "https://gitlab.com/api/v4/projects/${GITLAB_PROJECT_ID}/merge_requests?source_branch=${PR_SOURCE_BRANCH}" | jq '.[0].iid')
 
-          # Define title and WIP status
-          if [ "${PR_DRAFT}" = "true" ]; then
-            MR_TITLE="Draft: ${PR_TITLE}"
-            WIP="true"
-          else
-            MR_TITLE="${PR_TITLE}"
-            WIP="false"
-          fi
+            if [ -n "${MR_ID}" ]; then
+              echo "Found MR ID: ${MR_ID}, closing it..."
 
-          MR_ID=$(curl --silent --header "PRIVATE-TOKEN: ${{ secrets.GITLAB_TOKEN }}" \
-            "https://gitlab.com/api/v4/projects/${GITLAB_PROJECT_ID}/merge_requests?source_branch=${PR_SOURCE_BRANCH}" | jq '.[0].iid')
+              # Close the MR by updating its state to 'closed'
+              RESPONSE=$(curl --silent --write-out "HTTPSTATUS:%{http_code}" \
+                --header "PRIVATE-TOKEN: ${{ secrets.GITLAB_TOKEN }}" \
+                --header "Content-Type: application/json" \
+                --data '{"state_event": "close"}' \
+                --request PUT "https://gitlab.com/api/v4/projects/${GITLAB_PROJECT_ID}/merge_requests/${MR_ID}")
 
-          if [ -n "${MR_ID}" ]; then
-            # Update the Merge Request in GitLab
-            RESPONSE=$(curl --silent --write-out "HTTPSTATUS:%{http_code}" \
-              --header "PRIVATE-TOKEN: ${{ secrets.GITLAB_TOKEN }}" \
-              --header "Content-Type: application/json" \
-              --data '{
-                "title": "'"${MR_TITLE}"'",
-                "description": '"${FULL_DESCRIPTION_ESCAPED}"',
-                "work_in_progress": "'"${WIP}"'"
-              }' \
-              --request PUT "https://gitlab.com/api/v4/projects/${GITLAB_PROJECT_ID}/merge_requests/${MR_ID}")
+              HTTP_STATUS=$(echo "$RESPONSE" | tr -d '\n' | sed -e 's/.*HTTPSTATUS://')
 
-            # Extract the HTTP status code
-            HTTP_STATUS=$(echo "$RESPONSE" | tr -d '\n' | sed -e 's/.*HTTPSTATUS://')
+              # Log the response
+              echo "Response: ${RESPONSE}"
 
-            # Log the response for debugging
-            echo "Response: ${RESPONSE}"
-
-            # Validate the response
-            if [ "${HTTP_STATUS}" -ne 200 ]; then
-              echo "Failed to update Merge Request. HTTP Status Code: $HTTP_STATUS"
+              # Check if the request was successful
+              if [ "${HTTP_STATUS}" -ne 200 ]; then
+                echo "Failed to close GitLab MR. HTTP Status Code: $HTTP_STATUS"
+                exit 1
+              else
+                echo "Successfully closed GitLab MR."
+              fi
+            else
+              echo "No corresponding GitLab MR found for PR source branch."
               exit 1
             fi
           else
-            echo "Could not find a MR for this PR, make sure it is created."
-            exit 1
+            echo "PR was merged, not closing GitLab MR."
           fi
